### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dereuromark** [codekanzlei/cake-auth-actions#8]
This looks quite similar from the idea to
https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/Authorization.md

Are you still maintaining it, are you interested in upgrading to 5.x and adding it to the awesome list?

**Comment by felixkempf** [comment]
Hi and sry for the late answer,.

Yes, we are still maintaining it through active usage in our Cake 4 apps. 

I don't see us upgrading to and maintaining a 5.x version prior to 5.1 though. And even after that, I just stumbled upon a good looking alternative that we might use instead 😉
